### ISSUE TITLE
Injection of window object

### ISSUE THREAD

**Issue by Kalpesh300** [maciejtreder/ng-toolkit#351]
## I'm submitting a...
<pre><code>
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ x ] @ng-toolkit/universal
</code></pre>

## Current behavior
The issue is related to the injection of window object in the constructor. When you inject window object in the constructor it doesn't add  ' , ' to separate other injected objects.

## Expected behavior
It can be resolved by injecting window object at the end of all other injected objects or you can add  ' , '  for separation of injected objects.

**Comment by maciejtreder** [comment]
Hello. Thank you for this report. That will be quick fix. :)

**Comment by maciejtreder** [comment]
@Kalpesh300 I would never move adding params at the end of params list. The reason is simple. TypeScript will allow you to compile code like that:

```
constructor(something: string, somethingOther: string,) {}
```

While to compile this, not:

```
constructor(something: string,, somethingOther: string) {}
```

So adding param at the end, must be involved with checking if there is comma or not. It is much easier to just add it at the beginning.
