### ISSUE TITLE
 ng add @ng-toolkit/universal issue

### ISSUE THREAD

**Issue by itranga** [maciejtreder/ng-toolkit#416]
ranga@ranga:~/code/ranga/myAwesomeApp$ ng add @ng-toolkit/universal
Installing packages for tooling via npm.
INFO: Project property is set to 'myAwesomeApp'.
ERROR: Bootstrap not found in ./src/./app/app.browser.module.ts.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

Angular CLI: 6.1.3
Node: 8.11.3
OS: linux x64
Angular: 6.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.3
@angular-devkit/build-angular     0.7.3
@angular-devkit/build-optimizer   0.7.3
@angular-devkit/build-webpack     0.7.3
@angular-devkit/core              0.7.3
@angular-devkit/schematics        0.7.3
@angular/cdk                      6.4.5
@angular/cli                      6.1.3
@angular/material                 6.4.5
@ngtools/webpack                  6.1.3
@schematics/angular               0.7.3
@schematics/update                0.7.3
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2

**Comment by adskiremote** [comment]
Exactly the same happening to me.  I also tried the PWA starter, built and ran the server on localhost:8080.
SSR doesn't seem to be working.  I only see <app-root></app-root>  and no route html included.

**Comment by adskiremote** [comment]
Hi Macie,

thanks for getting back to me.

I used the default app `ng new --collection @ng-toolkit/init testFrontendApp`

The version I have installed is the latest - I installed it only 3 days ago.
The `app.browser.module.ts` exists and is as follows:

`import { NgModule } from '@angular/core';
import { BrowserModule, BrowserTransferStateModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { AppModule } from './app.module';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { ServiceWorkerModule } from '@angular/service-worker';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { TranslateLoader, TranslateModule } from '@ngx-translate/core';

export function HttpLoaderFactory(http: HttpClient) {
    return new TranslateHttpLoader(http);
}

@NgModule({
    bootstrap: [ AppComponent ],
    imports: [
        BrowserAnimationsModule,
        BrowserModule.withServerTransition({
            appId: 'app-root'
        }),
        AppModule,
        ServiceWorkerModule.register('/ngsw-worker.js'),
        HttpClientModule,
        TranslateModule.forRoot({
            loader: {provide: TranslateLoader, useFactory: HttpLoaderFactory, deps: [HttpClient]}
        }),
        BrowserTransferStateModule
    ]
})
export class AppBrowserModule {}
`

But when I build the code to test using...

`npm run build:prod
npm run server`

I only see the `<app-root></app-root>` in the source code and no other html elements inside from any route.

I did another test where I simply started a new Angular App via it's cli.

Then used your `ng add @ng-toolkit/universal`.  This worked.

However I wanted to use your complete PWA package to test and build upon rather than add Universal to an existing project.

If you need more information from me, please let me know. 

Many thanks!

**Comment by davidpales1** [comment]
npm i --save @angular/animations@8.1.2

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes.
