### ISSUE TITLE
Can I use this with Angular version 7.0.0?

### ISSUE THREAD

**Issue by Bodeclas** [maciejtreder/ng-toolkit#494]
Hello,

I am currently using Angular version 6.1.0. Can I use this in 7.0.0 version?

**Comment by abelokon955** [comment]
Right now when trying to add @ng-toolkit/universal to an angular 7.1 project we get the following dependency error:

`No matching version found for @nguniversal/module-map-ngfactory-loader@~7.1.0`

Obviously version 7.1.0 is yet not available for this module, is there a possibility to tell ng-toolkit to use the currently latest version 7.0.2?

**Comment by meywd** [comment]
any update on this?

**Comment by TheThingGoesSkraa** [comment]
I got the same issue with a Angular 7.1 project.

**Comment by markoddi** [comment]
any update on this?

**Comment by kaimikinkino** [comment]
I got them same issue

**Comment by HeMinzhang** [comment]
Maybe because [nguniversal/module-map-ngfactory-loader current version only 7.0.2](https://www.npmjs.com/package/@nguniversal/module-map-ngfactory-loader).

this [code
](https://github.com/maciejtreder/ng-toolkit/blob/master/schematics/universal/src/schematics.ts#L53) 
limit **nguniversal/module-map-ngfactory-loader version**

`addDependencyToPackageJson(tree, options, '@nguniversal/module-map-ngfactory-loader', angularVersion);`
