### ISSUE TITLE
Issue npm installing this toolkit

### ISSUE THREAD

**Issue by markoddi** [maciejtreder/ng-toolkit#527]
I did ng add @ng-toolkit/universal to my angular cli project.

Error I got: 

npm ERR! notarget No matching version found for @nguniversal/express-engine@^7.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

Thank you in advance.

**Comment by abovetempo** [comment]
It worked for me on angular 7.0.1 so I know it works on angular 7. I haven't tried past that version yet however.

**Comment by RegniBlef** [comment]
I have the same issue with my Angular project which I updated from v6 to v7. 
But it seems to work fine with projects that are already created with v7.

**Comment by abovetempo** [comment]
Good point if it makes a difference for me I upgraded from angular 6 to angular 7.0.1 and mine works. As I said before I haven't tried 7.1.0 yet though. I'm hoping to upgrade to it soon when I get the time.

**Comment by gaestradaaedo** [comment]
I have the same issue. I upgraded Angular from 5 to 6 to use this library and everything worked fine. Just as I was trying to install the library I got the error: 
<img width="737" alt="screen shot 2018-12-13 at 12 38 50" src="https://user-images.githubusercontent.com/41597873/49960421-bd2afb80-fed5-11e8-96a0-c856d80de3ea.png">

Do you know what the problem is @maciejtreder?

**Comment by markoddi** [comment]
thats the same terminal error I get

**Comment by HeMinzhang** [comment]
https://github.com/maciejtreder/ng-toolkit/pull/537
