### ISSUE TITLE
Document how to make android app from PWA

### ISSUE THREAD

**Issue by Vandivier** [maciejtreder/ng-toolkit#659]
## I'm submitting a...

<pre><code>
[X] Documentation issue or request
</code></pre>

## In package
<pre><code>
[X] @ng-toolkit/init
</code></pre>

## Current behavior

README says u can install on android

## Expected behavior

at least link to an article explaining how, or else add even more detail or a video link :)

also, does it also work for iPhone? why or why not

**Comment by KingDarBoja** [comment]
Hello @Vandivier,

If you run the **Angular Universal PWA boilerplate** generated by the `@ng-toolkit/init` package, you will see at your browser a small "plus" icon on the url section (at the right side). It is supposed to work like an installable application so you can install it on your phone. I do think it works for iPhone too since we rely on `@angular/pwa` capabilities.

Take a look at their official [documentation](https://angular.io/guide/service-worker-intro) to know more.

Cheers!
