### ISSUE TITLE
Facing issue for redirecting to domain name

### ISSUE THREAD

**Issue by darteam43** [maciejtreder/ng-toolkit#723]
I have deployed the application using ng-toolkit/universal. facing an issue with redirecting to the domain name from hhtps://example.com to https://www.example.com

**Comment by KingDarBoja** [comment]
@darteam43 If you are using `AWS`, I do recommend reading [Setup www domain redirect](https://serverless-stack.com/chapters/setup-www-domain-redirect.html) section at _https://serverless-stack.com/_.

Cheers!

**Comment by darteam43** [comment]
@KingDarBoja  Thank you for the reply, 

 we are using google cloud for our application and we have configured load balancing problem is we tried to redirect all the request using htaccess but the htaccess file is not working on the angular server

**Comment by KingDarBoja** [comment]
@darteam43 I really wanna help you but that is beyond my current knowledge on Google Cloud :( 

Maybe this StackOverflow[](https://stackoverflow.com/questions/38201969/redirecting-http-to-https-in-google-cloud/38202272) post could help you but not sure to be honest.

Also this kind of question should be better posted on StackOverflow because it is related to the server configuration and more people can help you with it 🤖

**Comment by darteam43** [comment]
@KingDarBoja 
 Thank you for your help will post a question in StackOverflow 
Have a nice day!
