### ISSUE TITLE
Error: Cannot find module 'require("./server/main")'

### ISSUE THREAD

**Issue by thenetimp** [maciejtreder/ng-toolkit#729]
## I'm submitting a...

<pre><code>
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

npm run server fails with an error

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'require("./server/main")'

## Expected behavior

should start the server.

## Minimal reproduction of the problem with instructions
ng new myproject
cd myproject
npm install @angular/platform-server --save
npm install @nguniversal/express-engine --save
ng add @ng-toolkit/universal
npm run build:prod
npm run server

## Example repository
https://github.com/openbridge/angular_ng_toolkit

## What is the motivation / use case for changing the behavior?

We'd like the library to work.

## Environment

<pre><code>
Angular version: X.Y.Z
@angular-devkit/architect                  0.803.19
@angular-devkit/build-angular              0.803.19
@angular-devkit/build-optimizer            0.803.19
@angular-devkit/build-webpack              0.803.19
@angular-devkit/core                       8.3.19
@angular-devkit/schematics                 8.3.19
@angular/cli                               8.3.19
@ngtools/webpack                           8.3.19
@nguniversal/common                        8.1.0
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.19
@schematics/update                         0.803.19
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.39.2
- Node version: v12.13.1
- Platform: MacOS, and AlpineLinux via Docker container
</code></pre>

**Comment by KingDarBoja** [comment]
Hello @thenetimp 

Did you ran `npm run build:ssr` before running `npm run server`?

**Comment by thenetimp** [comment]
I hadn't run ```npm run build:ssr```, but just did and got the same error.  I'll pull your repo and try it.

**Comment by KingDarBoja** [comment]
Yeah, I am pretty aware of some bugs on latest version due to `Angular/Universal` schematic changes, which I have addressed on my sample repo and expect to be applied on `ng-toolkit/universal` schematic too per #724.

Cheers!

**Comment by thenetimp** [comment]
Your sample repo is working.

**Comment by hymenoby** [comment]
Hello, 
I have the same issue. 

@KingDarBoja  i tried your repo and it works, can you tell please what are the changes you made?

**Comment by KingDarBoja** [comment]
@hymenoby Sure!

As the latest versions of `ng-toolkit/universal` (8.0.0 and above) were released to fix issues along with compatibility with Angular 8, the internal schematic `@nguniversal/express-engine`  got updated as well but unfortunately, I **didn't check** the changes being introduced on it, as I was too focused on fixing code generation and deployment steps.

So in order to ensure proper functionality, I read the entire documentation, made some sample repos using a fresh angular project and applied the same universal packages to spot differences between the old and new version.

Most of these changes were made on the `package.json` **scripts**, the `webpack.config` file (which I also changed to Typescript because why not?), the `server` and `prerender` files. Ah, don't forget to check out the `main.server` file because few import statements were moved from the `server` file into that, to avoid duplication of Angular instances on production.

Those files were once again updated to be ready for upcoming v9 of `@nguniversal/express-engine`, with few changes that I am too lazy to explain too but should be spotted on [Angular Universal release](https://github.com/angular/universal/releases) commits.

The breaking change that caused the error message  `Cannot find module 'require("./server/main")'` was the `externals` option on the `webpack.config` file, which I have no idea why it was included. Also using that breaks the serverless deployment so better to comment it out for the meantime.

Cheers!

**Comment by ingluca888** [comment]
I'm having the same error in Angular 8. I run these on an existing Angular 8 App:

npm run ng add @ng-toolkit/universal
npm run build:prod

with no errors, but when I run this:
 npm run server 

I get this error:
Error: Cannot find module 'require("./server/main")'

is there any fix for that.

I don't want to go through all the generated files. It might be much easier to use Angular Universal instead.

Thanks.

**Comment by hymenoby** [comment]
I had the same error, to solve it i had to go back to basic angular-universal;

just a few tips i had to use : 

1. In server.ts after the line 
`const DIST_FOLDER = join(process.cwd(), 'dist/browser');`
i added 
```
const domino = require('domino');
const fs = require('fs');
const path = require('path');
const template = fs.readFileSync(path.join(DIST_FOLDER, 'index.html')).toString();
const win = domino.createWindow(template);

global['window'] = win;
global['document'] = win.document;
global['DOMTokenList'] = win.DOMTokenList;
global['Node'] = win.Node;
global['Text'] = win.Text;
global['HTMLElement'] = win.HTMLElement;
global['navigator'] = win.navigator;
global['MutationObserver'] = getMockMutationObserver();
```
since i am using the window object in the code 

2. had to inject the document object every time i use it like this 
`constructor(@Inject(DOCUMENT) document: Document) {}`
and use it instead of just using the document object 

3. had to exclude all the code that required the brower and that i know would not work on SSR : 
First inject the platformID: 
`constructor(@Inject(PLATFORM_ID) private platformId: object) {}`

Then in the code exclude all the code that would not work on SSR : 
```
  if (isPlatformBrowser(this.platformId)) {
      if (_translateService.getBrowserLang()) {
        _translateService.use(_translateService.getBrowserLang());
      }
    } else {
      _translateService.use('en');
    }
```
In this case since i can't get the browser lang i excluded the code to get the browser lang and set a default lang on SSR.

Hope this helps

**Comment by ingluca888** [comment]
thanks, actually I fixed by commenting out the externals option (which is './dist/server/main': 'require("./server/main")') on the webpack.server.config.js file.

Now, I'm running into another error: 

Warning: Flex Layout loaded on the server without FlexLayoutServerModule
ERROR TypeError: Cannot read property 'match' of undefined

any idea?

**Comment by thenetimp** [comment]
Thanks, everyone.  With your help I was able to get a fresh angular application (no additional components) running in on AWS lambda.  

The fix for me was to remove the "externals option" from the webpack file.  I then had an issue with serverless part of ng-toolkit where I simply updated the webpack-cli module based on the version in the comment of this issue here. 

https://github.com/maciejtreder/ng-toolkit/issues/483#issuecomment-433185899

Now I can systematically take our existing application and port it into this new repository and hope nothing breaks in the process.  You all rock thanks for the help. 

PS I won't close the ticket, I'll leave that up to the decision of the maintainer.

**Comment by atul2210** [comment]
I am also having same issue.   Kindly help.  Thanks in advance.

**Comment by KingDarBoja** [comment]
> I am also having same issue.
> Commenting out in webpack.config solve this issue but getting another issue.

Hi mate, can you post your issue here? Maybe we can help you to find out what's going on.

**Comment by atul2210** [comment]
npm run build:prod
successfully built but 

error while running npm run server

node local.js

internal/modules/cjs/loader.js:716
    throw err;
    ^

Error: Cannot find module 'require("./server/main")'

Its really frustrating and showstopper for me.

**Comment by atul2210** [comment]
Commenting out in webpack.config solve this issue but getting below error.

Error: The selector "app-root" did not match any elements
    at platform_server_DefaultServerRenderer2.selectRootElement

**Comment by thenetimp** [comment]
That sounds like a bug in your code, I had something similar with a variable didn't have a function attached to it.  Look at that line in server.js and it should tell you what component the error is in and you should be able to debug it.

**Comment by atul2210** [comment]
> That sounds like a bug in your code, I had something similar with a variable didn't have a function attached to it. Look at that line in server.js and it should tell you what component the error is in and you should be able to debug it.

Okay! I'll check it. Thanks for your help and support.

**Comment by atul2210** [comment]
> That sounds like a bug in your code, I had something similar with a variable didn't have a function attached to it. Look at that line in server.js and it should tell you what component the error is in and you should be able to debug it.

I debugged it and now it is working fine :)  Thanks for your help and support.  :)

**Comment by atul2210** [comment]
I am getting following error message  after deploying Angular Universal App in IIS

**iisnode encountered an error when processing the request.

HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The node.exe process has not written any information to stderr or iisnode was unable to capture this information. Frequent reason is that the iisnode module is unable to create a log file to capture stdout and stderr output from node.exe. Please check that the identity of the IIS application pool running the node.js application has read and write access permissions to the directory on the server where the node.js application is located. Alternatively you can disable logging by setting system.webServer/iisnode/@loggingEnabled element of web.config to 'false'.**


Kindly help.

**Comment by KingDarBoja** [comment]
Hi @atul2210,

I do think it seems to be an issue related to the Angular Universal package but still I lack the knowledge on that service (IIS) so you should try to look for some help on some StackOverflow post.

I found a similar one already that could help you: [Deploy Angular Universal to IIS](https://stackoverflow.com/questions/49024686/deploy-angular-universal-to-iis).

Also, there is an issue on the Angular Universal repo too! [Hosting on IIS](https://github.com/angular/universal/issues/769#issuecomment-364952768).

**Comment by thenetimp** [comment]
For the IIS problem, you really should start your own support ticket instead of piggybacking off this one.

**Comment by ankit5577** [comment]
everything worked fine with me. I got rid of the error by correcting code in the 'server.js' file.

`module.exports = require("require(\"./server/main\")");`
to

`module.exports = require('./server/main');`
i used 'ng-toolkit/universal' and after running 'npm run server' i got same error.

**Comment by patrickbussmann** [comment]
Haha great idea @ankit5577 .
Its working with that change.
But why nobody fixes this issue? 😥

**Comment by ankit5577** [comment]
@patrickbussmann It's a compiler default behavior I guess.
as `require("require(\"./server/main\")");` contains 2 double-quotes,
 which will make `./server/main` a non-string as it will be out of double-quotes.
and As you know backslash is an escape character. so it tries to remove quotes within predefined quotes. 
`"\"X\"" = "X"`.
moreover, I believe this uses angular-cli as 'ng' command is used for bundling which technically makes it right as in typescript, libraries are imported using direct paths.
but yeah I got your point regarding `require()` issue. 
rest, let's see what they do. :/

**Comment by nicholas-davis** [comment]
Happening to me as well

**Comment by ankit5577** [comment]
> everything worked fine with me. I got rid of the error by correcting code in the 'server.js' file.
> 
> `module.exports = require("require(\"./server/main\")");`
> to
> 
> `module.exports = require('./server/main');`
> i used 'ng-toolkit/universal' and after running 'npm run server' i got same error.

@nicholas-davis
