### ISSUE TITLE
An unhandled exception occurred: Cannot assign to read only property '_showWarnings' of object '#<Object>'

### ISSUE THREAD

**Issue by lkpatir** [maciejtreder/ng-toolkit#730]
Hi,
Ng toolkit universal is successfully installed on my Angular 8 project but when I run the npm run build:ssr commnad, I get the below error: 
An unhandled exception occurred: Cannot assign to read only property '_showWarnings' of object '#<Object>'
PFA the complete sequence of error. After generating the main.js file only the error is triggered. I googled the topic but not found anything. What could be wrong ?
[Error.txt](https://github.com/maciejtreder/ng-toolkit/files/3874871/Error.txt)

**Comment by KingDarBoja** [comment]
Hi @lkpatir 

I would like to help you if you can provide a sample repo to look at. If not, I do recommend checking  my [sample repo](https://github.com/KingDarBoja/example-angular-ng-toolkit) as there are few issues regarding the `ng-toolkit/universal` package.
Some of them are already being fixed in upcoming version as soon as I get some free time to work on it.

Cheers.

**Comment by lkpatir** [comment]
Hi @KingDarBoja 
I have added you to my repo: https://github.com/lkpatir/ng-toolkit-universal-bug

**Comment by KingDarBoja** [comment]
@lkpatir Looks like you had a mismatch between `angular/cli` and `@angular-devkit/build-angular` version. 

Updating the dependencies fixes the issue. I recommend using [ncu tool](https://www.npmjs.com/package/npm-check-updates) in order to do that.

Cheers!

**Comment by lkpatir** [comment]
Hi @KingDarBoja 

Like you suggested, the error is gone after updating my Angular CLI to latest version. Thanks a bunch !!

**Comment by KingDarBoja** [comment]
Closing as resolved! 🚀
